version: '3.8'

services:
  website-hub:
    image: gwen124/website-hub:latest
    container_name: website-hub
    ports:
      - "8080:80"
    volumes:
      # 挂载主配置文件（必需）
      - ./config.yml:/config/config.yml:ro
      
      # 挂载网站配置（可选，如果使用外部网站配置）
      # - ./sites-config.json:/config/sites-config.json:ro
      
      # 挂载 footer 第二行链接配置（可选）
      - ./footer-links.json:/config/footer-links.json:ro
      
      # 挂载自定义字体（可选）
      - ./fonts:/config/fonts:ro
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai

