name = "navhub-oauth"
main = "index.js"
compatibility_date = "2024-01-01"

# 环境变量（请在 Cloudflare Dashboard 中配置实际值）
# [vars]
# GITHUB_CLIENT_ID = ""
# GITHUB_CLIENT_SECRET = ""  # 使用 wrangler secret put GITHUB_CLIENT_SECRET
# ALLOWED_ORIGINS = ""

